src/Entity/Cliente.php
<?php

namespace App\Entity;

use App\Repository\ClienteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClienteRepository::class)
 */
class Cliente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="bigint")
     */
    private $cod;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nome;

    /**
     * @ORM\Column(type="date")
     */
    private $nascimento;

    /**
     * @ORM\Column(type="string", length=14)
     */
    private $cpf;

    /**
     * @ORM\OneToOne(targetEntity=Acesso::class, mappedBy="cod_cliente", cascade={"persist", "remove"})
     */
    private $acesso;

    /**
     * @ORM\OneToOne(targetEntity=Endereco::class, mappedBy="cod_cliente", cascade={"persist", "remove"})
     */
    private $endereco;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCod(): ?string
    {
        return $this->cod;
    }

    public function setCod(string $cod): self
    {
        $this->cod = $cod;

        return $this;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(string $nome): self
    {
        $this->nome = $nome;

        return $this;
    }

    public function getNascimento(): ?\DateTimeInterface
    {
        return $this->nascimento;
    }

    public function setNascimento(\DateTimeInterface $nascimento): self
    {
        $this->nascimento = $nascimento;

        return $this;
    }

    public function getCpf(): ?string
    {
        return $this->cpf;
    }

    public function setCpf(string $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function getAcesso(): ?Acesso
    {
        return $this->acesso;
    }

    public function setAcesso(Acesso $acesso): self
    {
        $this->acesso = $acesso;

        // set the owning side of the relation if necessary
        if ($acesso->getCodCliente() !== $this) {
            $acesso->setCodCliente($this);
        }

        return $this;
    }

    public function getEndereco(): ?Endereco
    {
        return $this->endereco;
    }

    public function setEndereco(Endereco $endereco): self
    {
        $this->endereco = $endereco;

        // set the owning side of the relation if necessary
        if ($endereco->getCodCliente() !== $this) {
            $endereco->setCodCliente($this);
        }

        return $this;
    }
}

src/Entity/Endereco.php
<?php

namespace App\Entity;

use App\Repository\EnderecoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EnderecoRepository::class)
 */
class Endereco
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="bigint")
     */
    private $cod;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $logradouro;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero_imovel;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $complemento;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $bairro;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $cidade;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estado;

    /**
     * @ORM\Column(type="float")
     */
    private $latitude;

    /**
     * @ORM\Column(type="float")
     */
    private $longitude;

    /**
     * @ORM\OneToOne(targetEntity=Cliente::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $cod_cliente;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCod(): ?string
    {
        return $this->cod;
    }

    public function setCod(string $cod): self
    {
        $this->cod = $cod;

        return $this;
    }

    public function getLogradouro(): ?string
    {
        return $this->logradouro;
    }

    public function setLogradouro(string $logradouro): self
    {
        $this->logradouro = $logradouro;

        return $this;
    }

    public function getNumeroImovel(): ?int
    {
        return $this->numero_imovel;
    }

    public function setNumeroImovel(int $numero_imovel): self
    {
        $this->numero_imovel = $numero_imovel;

        return $this;
    }

    public function getComplemento(): ?string
    {
        return $this->complemento;
    }

    public function setComplemento(?string $complemento): self
    {
        $this->complemento = $complemento;

        return $this;
    }

    public function getBairro(): ?string
    {
        return $this->bairro;
    }

    public function setBairro(string $bairro): self
    {
        $this->bairro = $bairro;

        return $this;
    }

    public function getCidade(): ?string
    {
        return $this->cidade;
    }

    public function setCidade(string $cidade): self
    {
        $this->cidade = $cidade;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getCodCliente(): ?Cliente
    {
        return $this->cod_cliente;
    }

    public function setCodCliente(Cliente $cod_cliente): self
    {
        $this->cod_cliente = $cod_cliente;

        return $this;
    }

}

src/Form/ClienteType.php
<?php

namespace App\Form;

use App\Entity\Cliente;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClienteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('cod')
            ->add('nome')
            ->add('nascimento', BirthdayType::class, [
                'format' => 'dd/MM/yyyy',
                ])
            ->add('cpf', TextType::class, [
                'attr' => ['id' => 'customcpf'],
                'label' => "CPF"
            ])
            ->add('acesso', AcessoType::class, [
                
            ])
            ->add('endereco', EnderecoType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Cliente::class,
        ]);
    }
}

src/Controller/ClienteController.php
<?php

namespace App\Controller;

use App\Entity\Acesso;
use App\Entity\Cliente;
use App\Form\ClienteType;
use App\Repository\ClienteRepository;
use ContainerTSNGlnz\getAcessoControllerService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/cliente")
 */
class ClienteController extends AbstractController
{
    /**
     * @Route("/", name="cliente_index", methods={"GET"})
     */
    public function index(ClienteRepository $clienteRepository): Response
    {
        return $this->render('cliente/index.html.twig', [
            'clientes' => $clienteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="cliente_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $cliente = new Cliente();
        $form = $this->createForm(ClienteType::class, $cliente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            //var_dump($form->get('acesso')->getData()->getPassword());exit;

            $senha = md5($form->get('acesso')->getData()->getPassword());
            $cliente->getAcesso()->setPassword($senha);

            $entityManager->persist($cliente);
            $entityManager->flush();
            
            return $this->redirectToRoute('cliente_index');
        }

        return $this->render('cliente/new.html.twig', [
            'cliente' => $cliente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="cliente_show", methods={"GET"})
     */
    public function show(Cliente $cliente): Response
    {
        return $this->render('cliente/show.html.twig', [
            'cliente' => $cliente,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="cliente_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Cliente $cliente): Response
    {
        $form = $this->createForm(ClienteType::class, $cliente);
        $form->handleRequest($request);

        $senha = md5($form->get('acesso')->getData()->getPassword());
        $cliente->getAcesso()->setPassword($senha);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('cliente_index');
        }

        return $this->render('cliente/edit.html.twig', [
            'cliente' => $cliente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="cliente_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Cliente $cliente): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cliente->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($cliente);
            $entityManager->flush();
        }

        return $this->redirectToRoute('cliente_index');
    }
}

templates/cliente/_delete_form.html.twig
<form method="post" action="{{ path('cliente_delete', {'id': cliente.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cliente.id) }}">
    <button class="btn">Deletar</button>
</form>

templates/cliente/_form.html.twig
{{ form_start(form, {'attr': {'id': 'simpleform'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Salvar') }}</button>
{{ form_end(form) }}

templates/cliente/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cliente{% endblock %}

{% block body %}
    <h1>Editar Cliente</h1>
    
    {{ include('cliente/_form.html.twig', {'button_label': 'Atualizar'}) }}
   
    {{ include('cliente/_delete_form.html.twig') }} 

    <a href="{{ path('cliente_index') }}">Voltar</a>

    
{% endblock %}

templates/cliente/index.html.twig
{% extends 'base.html.twig' %}



{% block title %}Cliente index{% endblock %}


{% block body %}

    <h1>Clientes</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Cod</th>
                <th>Nome</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
        {% for cliente in clientes %}
            <tr>
                <td>{{ cliente.cod }}</td>
                <td>{{ cliente.nome }}</td>
                <td>
                    <a href="{{ path('cliente_show', {'id': cliente.id}) }}">Visualizar</a>
                    <a href="{{ path('cliente_edit', {'id': cliente.id}) }}">Editar</a>
                </td>
                <td>{{ include('cliente/_delete_form.html.twig') }} </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Nenhum cliente cadastrado.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('cliente_new') }}" >Novo Cliente</a>
{% endblock %}

templates/cliente/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cliente{% endblock %}

{% block body %}
    <h1>Criar novo Cliente</h1>

    {{ include('cliente/_form.html.twig') }}

    <a href="{{ path('cliente_index') }}">Voltar</a>
{% endblock %}

templates/cliente/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cliente{% endblock %}

{% block body %}
    <h1>Cliente</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Cod</th>
                <td>{{ cliente.cod }}</td>
            </tr>
            <tr>
                <th>Nome</th>
                <td>{{ cliente.nome }}</td>
            </tr>
            <tr>
                <th>Nascimento</th>
                <td>{{ cliente.nascimento ? cliente.nascimento|date('d-m-Y') : ''}}</td>
            </tr>
            <tr>
                <th>CPF</th>
                <td>{{ cliente.cpf }}</td>
            </tr>
            <tr>
                <th>Cod Acesso</th>
                <td>{{ cliente.acesso.cod }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ cliente.acesso.email }}</td>
            </tr>
            <tr>
                <th>Senha</th>
                <td>{{ cliente.acesso.password }}</td>
            </tr>
            <tr>
                <th>Cod Endereço</th>
                <td>{{ cliente.endereco.cod }}</td>
            </tr>
            <tr>
                <th>Logradouro</th>
                <td>{{ cliente.endereco.logradouro }}</td>
            </tr>
            <tr>
                <th>Numero Imovel</th>
                <td>{{ cliente.endereco.numeroImovel }}</td>
            </tr>
            <tr>
                <th>Complemento</th>
                <td>{{ cliente.endereco.complemento }}</td>
            </tr>
            <tr>
                <th>Bairro</th>
                <td>{{ cliente.endereco.bairro }}</td>
            </tr>
            <tr>
                <th>Cidade</th>
                <td>{{ cliente.endereco.cidade }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ cliente.endereco.estado }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ cliente.endereco.latitude }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ cliente.endereco.longitude }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('cliente_index') }}">Voltar</a>
{% endblock %}